- name: Build three-tier-app inventory
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Get openstack servers
    os_server_info:
      cloud: ospcloud
    register: r_os_server_info

  - name: Add hosts
    add_host:
      name: "{{ item.name }}"
      ansible_host: "{{ item.public_v4 }}"
      groups:
        - "{{ item.metadata.group }}"
        - "{{ item.metadata.deployment_name }}"
      ansible_user: cloud-user
      ansible_ssh_private_key_file: ~/.ssh/lab-id_rsa
    loop: "{{ r_os_server_info.openstack_servers }}"
    loop_control:
      label: "{{ item.name }}"

- import_playbook: ./main.yml
